### ISSUE TITLE
Cobra Issue: VAD-Performance with noise

### ISSUE THREAD

**Issue by bmt1596** [Picovoice/cobra#138]
Hello Picovoice Team. 

Currently, I am using Picovoice Cobra to detect voice from a walkie-talkie signal. Is there any way to improve the performance of Cobra? i noticed that the VAD flag is not set in cases where there is noise interference, specifically in this case, noise from the walkie-talkie signal. Could you give me some advice on how to address this issue? Could the interference from the walkie-talkie be disrupting the signal processing of Cobra? 

Attached is the WAV file we recorded. [voice_with_noise](https://drive.google.com/file/d/1kzdGGySYM0evk5hAzHWpRu0U3vvbWT7i/view?usp=share_link)

Tks so much!

**Comment by mrrostam** [comment]
This is what I got for the attached audio file, so if you are getting any other values, probably there is a bug in your code.

![Figure_1](https://user-images.githubusercontent.com/42750891/227326581-28f4f2d1-79ae-4e7a-9d34-cb159c4cae8b.png)

**Comment by bmt1596** [comment]
That's also good news because the Cobra can handle this radio signal. I will check my source Code again. Maybe the format is not standard or the buffer has lost some values.

As far as I know, Cobra processes each frame 512 Samples and 16kHz. Each Round i receive 64 Samples and have to wait 8 loops to get all 512 Samples before calling `pv_cobra_process`. Maybe somewhere is still not correct. I will check the Source code again and let you know the results as soon as possible.

**Comment by bmt1596** [comment]
I have checked my source code again when running experiments on the board and the returned values are very small and fluctuate only within the range of 0 to 0.02 - can you help me check if there is any mistake in my code? I am using the c libpv_cobra.so library

I initialize cobra as follows:
` 
  std::ofstream file;
  file.open("cobra_Buf.txt");
  unsigned int cnt = 0;

 // Init Pv_cobra
  int16_t   bufCobra          [512] = { 0 };
  int16_t   bufDownlink_48kHz [192] = { 0 };
  int16_t   bufDownlink_16kHz [64]  = { 0 };
  bool isPvCobraReady = false;
  
  
  pv_status_t pvCoBraStatusInit = pv_cobra_init(accessKey.c_str(), &cobra_handle);

  if (pvCoBraStatusInit != PV_STATUS_SUCCESS)
  {
    audioProcLogger.errorStream << "Cobra VAD could not be initialized."
        << std::endl;
    audioProcLogger.errorStream << "Cobra VAD Init Status: "
        << pvCoBraStatusInit << std::endl;
    isPvCobraReady = false;
  }
  else
  {
    audioProcLogger.debugStream << "Cobra VAD initialized." << std::endl;
    audioProcLogger.debugStream << "Cobra VAD Ancor: " << pv_cobra_version()
        << std::endl;
    audioProcLogger.debugStream << "Cobra VAD Ancor: " << pv_cobra_frame_length()
        << std::endl;
    isPvCobraReady = true;
  }`

In the while loop, my source code is as follows:

`
readBufDownlink();

// convert downlink buf from 48 kHz to 16 kHz (downsampling)
    for (unsigned int i = 0; i < 64; i++)
    {
      bufDownlink_16kHz[i] = bufDownlink_48kHz[3 * i];
    }

    // 8 Round of bufDownlink_16kHz ( 64 Samples * 8 = 512 Samples) and set all samples to bufCobra
    memcpy(&bufCobra[(cnt - 1) * 64], &bufDownlink_16kHz[0],
        64 * sizeof(short));

    // Pico-Voice Process
    if (cnt >= 8)
    {
      if (isPvCobraReady)
      {
        pv_cobra_process(cobra_handle, bufCobra, &is_voice);

        if (bCBdownDetected)
        {
          for (int i = 0; i < 512; i++)
          {
            // save all Samples to file
            file << bufCobra[i] << std::endl;
          }
          printf("%lf\n", is_voice);
        }

        if (is_voice > 0.9f)
        {
          vad = true;
        }
        else
        {
          vad = false;
        }
      }
      cnt = 0;
    }
cnt++;
`
