### ISSUE TITLE
Cobra's dependence on input signal strength

### ISSUE THREAD

**Issue by bmt1596** [Picovoice/cobra#141]
Hello Picovoice Team!

After testing with Cobra, I have found the following:

The performance of Cobra decreases gradually and the voice becomes harder to recognize when I divide the signal into smaller portions. This makes it difficult for us to determine a fixed volume level for Cobra to operate most effectively because the signal volume from the microphone is constantly changing. Is this a bug or is it normal?

Below is a chart showing the VAD output of the original signal and the signal divided by 10.
![VAD](https://user-images.githubusercontent.com/55514665/232422792-e537800b-57c1-4c43-a3ae-ff566cc41596.jpg)

Thank you.

**Comment by kenarsa** [comment]
Can you somehow share the files corresponding to these outputs?

**Comment by bmt1596** [comment]
Hi @kenarsa thank you, here are 2 corresponding files for the above chart, can you check it?
[cobra_voice_test.wav](https://drive.google.com/file/d/1pj0Vf_efx8QjlhzuEEnJelbXQxrOx3P6/view) and [cobra_voice_test_div10](https://drive.google.com/file/d/1jH2m6EJ_lePig-WtzArCH1YiHxIPDw96/view)

**Comment by bmt1596** [comment]
Hi @kenarsa Hi kenarsa. For the cobra_voice_test file, I used the recording function and recorded the values ​​of the samples in the range [-1 1]. Then I experimented with the Matlab function and split the samples from the cobra_test_voice file 10 times smaller. After getting new samples 10 times smaller I again generate cobra_voice_test_div10 file from Matlab via audiowrite function.

After experimenting with different divisions and looking through Matlab, I found that Cobra returns different VAD ouput values.


Does the Wave file when put into cobra process must always be in the range [-1 1] to bring the best performance?

**Comment by kenarsa** [comment]
There is something off with the microphone (recording setup). The high-frequency content is cut off. The gain isn't the main issue here. I am closing for now, but if you get a good recording showing the same degradation with only gain manipulation, please re-open it, and we will look into it. Thanks!

**Comment by bmt1596** [comment]
Hi @kenarsa . Here I have a recording used by the high-end  [Zoom H8 Audio Recorder](https://zoomcorp.com/de/de/handy-recorder/handheld-recorders/h8/) and the audio file is also of high quality with full higher content frequency. Similar to the experiment above, after dividing the samples into 10 parts, I noticed that the result of Picovoice Cobra had changed. I think you can also test and verify the results through my wave file: 

[H8_Handy_Recorder.wav](https://drive.google.com/file/d/1sCJ_7RghUhIYUQHB_Od2_YLAT62BsjSe/view?usp=sharing) 

Below is a chart showing the VAD output of the original signal and the signal divided by 10:
![VADouput](https://user-images.githubusercontent.com/55514665/234289666-5ca8e40c-41d6-49d3-8d4d-f76eefeb90db.jpg)

I am looking forward to your feedback and how to fix it. Thank you so much.

**Comment by bmt1596** [comment]
Hi @kenarsa . Sorry about the duplicate. Because I can't reopen this issue. 

Here I have a recording used by the high-end  [Zoom H8 Audio Recorder](https://zoomcorp.com/de/de/handy-recorder/handheld-recorders/h8/) and the audio file is also of high quality with full higher content frequency. Similar to the experiment above, after dividing the samples into 10 parts, I noticed that the result of Picovoice Cobra had changed. I think you can also test and verify the results through my wave file: 

[H8_Handy_Recorder.wav](https://drive.google.com/file/d/1sCJ_7RghUhIYUQHB_Od2_YLAT62BsjSe/view?usp=sharing) 

Below is a chart showing the VAD output of the original signal and the signal divided by 10:
![VADouput](https://user-images.githubusercontent.com/55514665/234289666-5ca8e40c-41d6-49d3-8d4d-f76eefeb90db.jpg)

I am looking forward to your feedback and how to fix it. Thank you so much.
