### ISSUE TITLE
SDK for Unity Game Engine?

### ISSUE THREAD

**Issue by VulgoRox** [Picovoice/cobra#152]
**Is your feature request related to a problem? Please describe.**
Not really.

**Describe the solution you'd like**
A more easy to implement SDK for the Unity Game Engine.

**Describe alternatives you've considered**
I can probably just write the plugins my self, I just have no idea how too.

**Comment by laves** [comment]
@VulgoRox  - thanks for your input. Unfortunately, new bindings for Cobra are not on our immediate roadmap. I'll leave this issue open though and if there's enough traction, we may consider upgrading the priority. PRs are also welcome if you are feeling extra motivated on this one!

**Comment by rootux** [comment]
@laves any updates on this? @VulgoRox knows anyone who implemented this eventually?
