### ISSUE TITLE
Node Version

### ISSUE THREAD

**Issue by xC0der** [Picovoice/cobra#166]
Is there any chance of getting a supported version for Node?  Thanks!

**Comment by laves** [comment]
Unfortunately, this isn't on our immediate roadmap. If you are a commercial customer, reach out to your account manager and we'll see what can be arranged.

**Comment by xC0der** [comment]
Thanks for the response. It's too bad, as it looks like the only piece missing for a node implementation of smart speakers that are in your blog posts as both Leopard and porcupine have it. I totally get it tho, thanks again.
