### ISSUE TITLE
Cobra Issue: error when using with node.js for a server

### ISSUE THREAD

**Issue by OscarMFlorez** [Picovoice/cobra#168]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Actual behaviour
after installing the sdk and trying to use it, I'm getting this error:
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module '@picovoice/cobra-web'
Require stack:

### Steps to reproduce the behaviour

(Include enough details so that the issue can be reproduced independently.)

**Comment by ksyeo1010** [comment]
How did you install it, how are you using it? need more info.

**Comment by OscarMFlorez** [comment]
I installed it with npm install --save @picovoice/cobra-web
I'm running my serve on linux
importing like this:
const CobraWorker = require('@picovoice/cobra-web');
and then getting the error

**Comment by ksyeo1010** [comment]
Is this for a node.js backend project or frontend?

**Comment by OscarMFlorez** [comment]
Node.js backend

**Comment by ksyeo1010** [comment]
As mentioned here https://github.com/Picovoice/cobra/tree/main/binding/web#compatibility, `Cobra-web` is for web only. Cobra has no support for Node.js at the moment.
