### ISSUE TITLE
Implement `std::error::Error` for `CobraError` in Rust binding

### ISSUE THREAD

**Issue by kolektiv** [Picovoice/cobra#187]
**Is your feature request related to a problem? Please describe.**
`CobraError` does not implement the standard `std::error::Error` trait, which means that the use of the `?` syntax in `Result` returning functions is not available.

**Describe the solution you'd like**
Implement `std::error::Error` for `CobraError`. As the type already implements `Display`, it may literally be as simple as adding `impl std::error::Error for CobraError {}`, and relying on the provided functions - possibly a literal one-liner.

**Describe alternatives you've considered**
It is possible to workaround this by simply mapping the error, but it's a shame to need to, and a pity for a small and otherwise quite ergonomic library (although some more Rust-like changes to the API would be possible).

**Additional context**
n/a

**Comment by ErisMik** [comment]
Hi @kolektiv, thanks for the suggestion. We intended to implement `std::error::Error` for the error classes in all our bindings but Cobra seemed to have been missing it. I've uploaded a new version of the package with the fix, version [2.0.1](https://crates.io/crates/pv_cobra).

**Comment by kolektiv** [comment]
Thanks folks, it's such a small change, and it's not like it makes a huge difference, but a little bit less noise across multiple codebases - always good! Cheers.
