### ISSUE TITLE
Cobra Issue: On IOS there is a constant error "WARN  Sending `frame_sent` with no listeners registered." (BTW and on Android it works fine).

### ISSUE THREAD

**Issue by frymanofer** [Picovoice/cobra#211]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Cobra docs
- [X] I have searched the existing issues for Cobra

### SDK

iOS

### Cobra package version

2.0.1

### Framework version

EXPO CLI 0.17.8

### Platform

iOS

### OS/Browser version

N/A

### Describe the bug

I use your example of Cobra for IOS . It works however I keep getting endless warning messages:
"WARN  Sending `frame_sent` with no listeners registered."
On android it works fine.

### Steps To Reproduce

It is reproducible on my environment. On simulator and real devices. Just run the IOS example and watch terminal console for messages.

### Expected Behavior

Not to receive the warning messages ""WARN  Sending `frame_sent` with no listeners registered." or a better message that explains where this is in the stack etc'

**Comment by albho** [comment]
Could you give our [iOS Demo](https://github.com/Picovoice/cobra/blob/main/README.md#ios-demos) a try and see if you get the same issue?

**Comment by frymanofer** [comment]
Can you send me exact instruction. The IOS demo starts with pod install - what do you want me to download before that?

**Comment by frymanofer** [comment]
Hi All - I managed to find my problem and solve it.
This happens when the app closes or crashes without properly stop Cobra and then I start Cobra again. 
If I make sure I stop / delete everything than all works fine. Another alternative is to call stop Cobra before you start it to make sure it was not left open from another run.
Thanks,
Ofer
