### ISSUE TITLE
Cobra implementation doubt: continuously alternating between 2 audio sources  

### ISSUE THREAD

**Issue by PrathamG** [Picovoice/cobra#213]
I have 2 separate mono mics that are placed in different locations. In every iteration of an infinite loop, I collect samples from the mics separately, run VAD on mic1 data first, and then run VAD on mic2 data.

For this use case, do I need to have 2 separate instances of cobra, or will one instance effectively perform VAD on alternating mic1 and mic2 samples?

**Comment by ksyeo1010** [comment]
Yes you will need two instances of cobra, one for each mic source.
