### ISSUE TITLE
Cobra Issue:  integrating Cobra with Next.js project

### ISSUE THREAD

**Issue by tval2** [Picovoice/cobra#220]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Cobra docs
- [X] I have searched the existing issues for Cobra

### SDK

Node.js

### Cobra package version

"@picovoice/cobra-node": "^2.0.1"

### Framework version

Node v21.6.0 | Next.js v14.2.4

### Platform

macOS (x86_64, arm64)

### OS/Browser version

macOS Sonoma 14.4.1 | Apple M3 Pro Chip | Chrome

### Describe the bug

I don't have a ton of experience with Node but I simply have a starter template next.js project up (the newer router architecture) and in my route.ts file I have this very basic code that was mostly stolen from Picovoice's lone Node example in the API docs:

```
import { NextRequest, NextResponse } from "next/server";
import { Cobra } from "@picovoice/cobra-node";

const PICOVOICE_API_KEY = process.env.PICOVOICE_API_KEY!;

let cobra: Cobra | null = null;

export async function POST(req: NextRequest) {
  if (!cobra) {
    cobra = new Cobra(PICOVOICE_API_KEY);
  }

  const audioData = await req.arrayBuffer();
  const int16Array = new Int16Array(audioData);

  try {
    const voiceProbability = cobra.process(int16Array);
    return NextResponse.json({ voiceProbability });
  } catch (error) {
    console.error("Error processing audio for VAD:", error);
    return NextResponse.json(
      { error: "Failed to process audio for VAD" },
      { status: 500 }
    );
  }
}

process.on("exit", () => {
  if (cobra) {
    cobra.release();
  }
});
```

but the second that fetch is called on this API from the front end I get this error

``` 
⨯ CobraInvalidArgumentError: File not found at "libraryPath": /Users/<me>/<my_project>/.next/server/lib/mac/arm64/pv_cobra.node
    at new Cobra (webpack-internal:///(rsc)/./node_modules/@picovoice/cobra-node/dist/cobra.js:45:19)
    at POST (webpack-internal:///(rsc)/./src/app/api/vad/route.ts:13:17)
    at /Users/<me>/<my_project>/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:55044
```
    
 which, at least to me with limited knowledge of Node, is indicating that Picovoice is searching for the library under `.next/server.` The file pv_cobra.node exists at node_modules/@picovoice/cobra-node/lib/mac/arm64. But also the error said ".next/server" not "node_modules/@picovoice/cobra-node". There is not a lib folder under ".next/server." I'm sure there are some manual things I could do to force it but if the rest of my team wants to use this package with a simple `npm install @picovoice/cobra-node` then I feel like I have to missing something obvious here.

One note* I do get that `CobraInvalidArgumentError` is throw so the library is being read in. It's just in cobra.js when it looks for the path again.

### Steps To Reproduce

1. Create a next.js typescript project with router architecture (maybe on a Macbook Pro M3? I feel like it shouldn't matter)
2. npm install @picovoice/cobra-node and paste my code above into a route.ts file under api/vad/route.ts
3. call fetch on this from the frontend
4. start debugger mode and it should file while trying to compile

### Expected Behavior

Load in the constructor without error.

**Comment by tval2** [comment]
I can also confirm that this is specifically an issue with the compatibility of picovoice and next.js since I created a test.ts file and pasted the same code in there and it works fine. I also tried the mic.js demo and that works as well.

I understand I can manually provide `libraryPath` to the Cobra instance but I'd like to avoid that since the file path will be different for different people and devices so it feels a bit like a weak bandaid solution

**Comment by albho** [comment]
@tval2 - I see the issue: we use `__dirname` [here](https://github.com/Picovoice/cobra/blob/main/binding/nodejs/src/platforms.ts) to figure out where the appropriate lib file is, and it seems like this [doesn't work with next.js](https://nextjs.org/docs/pages/api-reference/functions/get-static-props#reading-files-use-processcwd).

Unfortunately, since we don't officially support next.js, you'd have to use `libraryPath`.

**Comment by tval2** [comment]
@albho thanks for getting back! I appreciate the support here. I was digging yesterday and found the same thing. I'm trying to make it robust across platforms but even when using `process.cwd()` like in this snippet:

```
async function initializeCobra() {
  if (cobra) return;

  const platform = os.platform();
  const arch = os.arch();

  let libraryPath = path.join(
    process.cwd(),
    "node_modules",
    "@picovoice",
    "cobra-node",
    "lib"
  );

  if (platform === "win32") {
    libraryPath = path.join(libraryPath, "windows", arch, "pv_cobra.dll");
  } else if (platform === "darwin") {
    libraryPath = path.join(libraryPath, "mac", arch, "pv_cobra.node");
  } else if (platform === "linux") {
    libraryPath = path.join(libraryPath, "linux", arch, "pv_cobra.so");
  } else {
    throw new Error(`Unsupported platform: ${platform}`);
  }

  const { Cobra } = await require("@picovoice/cobra-node") // import("@picovoice/cobra-node");
  cobra = new Cobra(PICOVOICE_API_KEY, { libraryPath });
}
```

it still gives the `Error: Cannot find module ` issue. When you said I'd have to use `libraryPath` was this what you meant or are users supposed to do it in a different way?

**Comment by tval2** [comment]
for anyone out there who reads this and is facing the same issue, looks like the fix was to put this in the `next.config.js` file:

```
const nextConfig = {
  webpack: (config, { isServer }) => {
    config.resolve.fallback = { fs: false };

    if (isServer) {
      config.externals.push({
        "@picovoice/cobra-node": "commonjs @picovoice/cobra-node",
      });
    }

    return config;
  },
};

module.exports = nextConfig;
```

this combined with the above did the trick for me. I'm still having issues with pvrecorder but hopefully this helps someone out there!

**Comment by albho** [comment]
Glad you figured it out and thanks for sharing your solution! If you continue to have issues with pvrecorder, please feel free to open an issue in the [pvrecorder repo](https://github.com/Picovoice/pvrecorder/issues/).
