### ISSUE TITLE
Cobra Issue: Flutter support for cobra

### ISSUE THREAD

**Issue by mhamdan91** [Picovoice/cobra#221]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Cobra docs
- [X] I have searched the existing issues for Cobra

### SDK

Android

### Cobra package version

does not matter

### Framework version

does not matter

### Platform

Android

### OS/Browser version

does not matter

### Describe the bug

Could you add flutter support for cobra? I've evaluated the model against other models and it definitely stands out, so I'd appreciate it if you'd make a flutter package available for it.

### Steps To Reproduce

NA

### Expected Behavior

NA

**Comment by matt200-ok** [comment]
Hello @mhamdan91, unfortunately we do not support flutter for Cobra. If this is for a commercial product you can reach out to your sales contact at Picovoice, or otherwise contact us through sales to get the feature added.
