### ISSUE TITLE
Cobra Issue: file lib/raspberry-pi/cortex-a53-aarch64/libpv_cobra.so corrupted

### ISSUE THREAD

**Issue by randy-lcs** [Picovoice/cobra#66]
Expected an ELF format file of approximately the same size as other shared libraries.

This file shrank by about half since the previous version, and does not appear to be an ELF file at all.

**Comment by kenarsa** [comment]
Can you provide the actual error as well?

**Comment by randy-lcs** [comment]
There is no error other than the fact that this file will not load. This is an ar format file, which includes the contents of all of your individual compiled source files with all of their symbols. Whoever did the build that produced this apparently skipped a step.

-Randy

**Comment by laves** [comment]
Thanks for reporting @randy-lcs - the correct file is in the repo now.

**Comment by randy-lcs** [comment]
Thanks for fixing this. Unfortunately, I'm getting ACTIVATION LIMIT REACHED
errors, even though I haven't actually gotten it to work yet. Maybe due to
my several unsuccessful attempts? The page for my Access Key shows 0 of
72000 seconds of usage, and 3 of 3 devices. I've only tried it on one
device, over and over, so perhaps this is somehow miscounting my devices?
It's very disappointing to get this far, but be able to even try it.

Thanks for any light you can shed on this.

-Randy

**Comment by kenarsa** [comment]
can you email your `AccessKey` to hello@picovoice.ai? Then we can look deeper and see what happened.

**Comment by randy-lcs** [comment]
Sure. My access key
is 4tWSX9TyM+fqRGgyR6PxqDq6ReBh3t9gLs7oH/zy5FquuVctr17W9Q==

Thanks,
-Randy

**Comment by laves** [comment]
@randy-lcs, please avoid sharing your `AccessKey` in public forums - we prefer email for support issues where an AccessKey needs to be shared.

We've looked into it and from what we see in our system, there are three unique devices registered under your AccessKey. We can free up devices if this indeed is an error on our end, but first I just wanted to ask you a couple of questions:
- What platform are you running on? (I assume RPi3-64, but I just want to double-check)
- What OS and OS version are you running?
- Did you swap SD cards at all during your attempt to use Cobra?
- Did you reinstall or update your OS during your attempt to use Cobra?
- Were you rebooting the system frequently?

Thanks!

**Comment by randy-lcs** [comment]
Sorry, I didn't realize this was public--I'm just using GMail.

I'm running on Linux 5.4.70, on a small device whose hardware is mostly the
same as a Raspberry Pi 3-64. There are no SD cards involved. We did switch
to a different Linux version recently. I reinstall it and reboot very
frequently.

-Randy

**Comment by randy-lcs** [comment]
P.S. As I mentioned before, I hadn't realized this was going into anything
public. Please invalidate my access key.

-Randy

**Comment by laves** [comment]
Can you provide a link to the device that you are using (if it is publicly available)?. Unfortunately, it might be the case that we are unable to support your device, but we'd like to look into this further.

**Comment by randy-lcs** [comment]
Could we take this to email? I'd rather not discuss this more here.

Thanks,
-Randy

**Comment by laves** [comment]
Of course - please email hello@picovoice.ai for further support. I'm going to close this issue since the original issue has been resolved and this new one is moving to email.
