### ISSUE TITLE
VAD offline

### ISSUE THREAD

**Issue by seekingdeep** [Picovoice/cobra#77]
Hi there,
can VAD be ran offline without the need of access keys, etc..
will the models be released publicly

**Comment by kenarsa** [comment]
VAD do run office even when you are using an `AccessKey`. The voice processing is 100% offline and the engine only needs connectivity once a couple of weeks or so to check the number of devices the user with `AccessKey` is using to assure they are within their allowed limit.

**Comment by danhalliday** [comment]
@kenarsa Can you elaborate on this? For example, if I used Cobra in a mobile app and happened to have a user who only ever launched my app offline, would Cobra work for them?

If not, when would it fail? Immediately on first launch, or later after some weeks of not being able to phone home? Is there any error state I can check to find out if Cobra isn’t working? Would that just be checking whether the initial call to create a Cobra instance succeeded? Does that call ever block on network access?

**Comment by kenarsa** [comment]
@danhalliday

No, the app needs internet connectivity at launch (i.e. when you call Cobra's init function for the first time). If it is not connected, then you get an `activation error` and you can totally catch it. Once init succeeds the app can be offline for a couple of weeks and then need connectivity again to be able to run for another couple of weeks.
